### PR TITLE
Introduce vagrant for local test

### PR DESCRIPTION
**Pull request by Koisell**
We introduce a Vagrantfile which allow to test locally without special
privileges. We introduce two scripts in order to switch from the CI mode
(the default one) and the vagrant mode.

### CODE REVIEW

**Comment by djspiewak** [comment]
Ooooh this is quite exciting! I have some changes that to suggest though as soon as I have some time (later today). Thanks!

**Comment by nicflores** [comment]
It's too bad we can't exercise vagrant during a travis build, travis has no support for it. It does support docker though, maybe later one we can add docker ssh tests.

**Comment by Koisell** [comment]
I initially made this to enable me to test locally. I will investigate how to do this with docker since I perfer having the same tools in all environments.

**Comment by nicflores** [comment]
You certainly don't have to, it was just a thought I had while going over this PR and just left a note to ourselves. Travis doesn't support vagrant bu they do support docker. If we had something similar to this PR with docker we could add it to our travis build. I think this container would help: https://hub.docker.com/r/panubo/sshd

**Comment by Koisell** [comment]
I already managed to create a working container that allow us to run test. I will look how we automate the creation and deletion of it before and after the test later in the evening.

**Comment by Koisell** [comment]
I'm closing this PR since I have now made a docker version. See https://github.com/slamdata/fs2-ssh/pull/9

**Pull request closed without merging**
